const ACTION_TYPES = {
  SET_TOKENS: 'SET_TOKENS',
  RESTORE_BAG: 'RESTORE_BAG',
  RESTORE_USER: 'RESTORE_USER',
  ADD_TO_BAG: 'ADD_TO_BAG',
  REMOVE_FROM_BAG: 'REMOVE_FROM_BAG',
  CLEAR_BAG: 'CLEAR_BAG',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
  SAVE_NOTIFICATIONS: 'SAVE_NOTIFICATIONS',
};

export default ACTION_TYPES;
