const ACTION_TYPES = {
  SET_TOKENS: 'SET_TOKENS',
  RESTORE_BAG: 'RESTORE_BAG',
  ADD_TO_BAG: 'ADD_TO_BAG',
  REMOVE_FROM_BAG: 'REMOVE_FROM_BAG',
  UPDATE_QUANTITY: 'UPDATE_QUANTITY',
};

export default ACTION_TYPES;
